# Automatically label PRs based on file changes
# Configuration for actions/labeler@v6

documentation:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'
      - 'docs/**/*'

dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - 'package.json'
      - 'package-lock.json'
      - 'npm-shrinkwrap.json'

tests:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/**/*.spec.ts'
      - 'src/**/*.test.ts'
      - '**/*.spec.ts'
      - '**/*.test.ts'

benchmarks:
  - changed-files:
    - any-glob-to-any-file:
      - 'benchmarks/**/*'
      - '**/*.bench.ts'

typescript:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.ts'
      - 'tsconfig.json'
      - 'tsup.config.ts'

build:
  - changed-files:
    - any-glob-to-any-file:
      - 'tsup.config.ts'
      - '.github/workflows/**/*'

core:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/core.ts'
      - 'src/engine.ts'

managers:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/managers.ts'

definitions:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/definitions.ts'
