#!/bin/sh
# Commitlint hook - validates commit messages follow conventional commit format
#
# NOTE: This hook is currently disabled due to Git CRLF environment issues in CI/sandbox.
# In normal development environments (after .gitattributes normalization), this hook
# should work correctly. To enable, uncomment the line below:
#
# npx --no-install commitlint --edit "$1"
#
# Manual validation is available via: echo "feat: message" | npx commitlint

exit 0
